defaults: &defaults
  protocol:
    username:
      key: "username"
      value: "raoxing"
    password:
      key: "password"
      value: "penglei3777"
    command:
      key: "command"
      deploy: "Deploy"
      rollback: "Rollback"
    host: "host"
    directory: "directory"
    config:
      key: "config"
      value: "http://svn.simba.taobao.com/svn/Apsara/galaxy/trunk2/online/online_confs/aggregator_recommend/"
    package: "package"

  package_name:
    rec_package: "resys_agg_recommend"
    rerank_package: "resys_agg_rerank"
    site_package: "resys_site_config"
    item_package: "resys_item_common_lib_data"
    trim_package: "resys_title_trim"
    query_package: "resys_top_query"
    aliguess_package: "resys_aliguess_data"
    filter_package: "resys_common_result_filter_data"
    indepsite_package: "resys_indep_site"
    ibcf_package: "resys_ibcf_site"

  release_address: "http://10.250.12.70/galaxy_release/"

  deploy_datum_status:
    new:     "New"
    ready:   "Ready"
    finish:  "Finish"
    failed:  "Failed"

  deploy_machine_status:
    active:  "Active"
    dead:    "Dead"
    running: "Running"
    deploy_success:   "Deploy Success"
    deploy_failed:    "Deploy Failed"
    rollback_success: "Rollback Success"
    rollback_failed:  "Rollback Failed"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
