require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeployDataController do

  # This should return the minimal set of attributes required to create a valid
  # DeployDatum. As you add validations to DeployDatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "agg_config" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeployDataController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all deploy_data as @deploy_data" do
      deploy_datum = DeployDatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:deploy_data).should eq([deploy_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested deploy_datum as @deploy_datum" do
      deploy_datum = DeployDatum.create! valid_attributes
      get :show, {:id => deploy_datum.to_param}, valid_session
      assigns(:deploy_datum).should eq(deploy_datum)
    end
  end

  describe "GET new" do
    it "assigns a new deploy_datum as @deploy_datum" do
      get :new, {}, valid_session
      assigns(:deploy_datum).should be_a_new(DeployDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested deploy_datum as @deploy_datum" do
      deploy_datum = DeployDatum.create! valid_attributes
      get :edit, {:id => deploy_datum.to_param}, valid_session
      assigns(:deploy_datum).should eq(deploy_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeployDatum" do
        expect {
          post :create, {:deploy_datum => valid_attributes}, valid_session
        }.to change(DeployDatum, :count).by(1)
      end

      it "assigns a newly created deploy_datum as @deploy_datum" do
        post :create, {:deploy_datum => valid_attributes}, valid_session
        assigns(:deploy_datum).should be_a(DeployDatum)
        assigns(:deploy_datum).should be_persisted
      end

      it "redirects to the created deploy_datum" do
        post :create, {:deploy_datum => valid_attributes}, valid_session
        response.should redirect_to(DeployDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved deploy_datum as @deploy_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeployDatum.any_instance.stub(:save).and_return(false)
        post :create, {:deploy_datum => { "agg_config" => "invalid value" }}, valid_session
        assigns(:deploy_datum).should be_a_new(DeployDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeployDatum.any_instance.stub(:save).and_return(false)
        post :create, {:deploy_datum => { "agg_config" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested deploy_datum" do
        deploy_datum = DeployDatum.create! valid_attributes
        # Assuming there are no other deploy_data in the database, this
        # specifies that the DeployDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeployDatum.any_instance.should_receive(:update_attributes).with({ "agg_config" => "MyString" })
        put :update, {:id => deploy_datum.to_param, :deploy_datum => { "agg_config" => "MyString" }}, valid_session
      end

      it "assigns the requested deploy_datum as @deploy_datum" do
        deploy_datum = DeployDatum.create! valid_attributes
        put :update, {:id => deploy_datum.to_param, :deploy_datum => valid_attributes}, valid_session
        assigns(:deploy_datum).should eq(deploy_datum)
      end

      it "redirects to the deploy_datum" do
        deploy_datum = DeployDatum.create! valid_attributes
        put :update, {:id => deploy_datum.to_param, :deploy_datum => valid_attributes}, valid_session
        response.should redirect_to(deploy_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the deploy_datum as @deploy_datum" do
        deploy_datum = DeployDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeployDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => deploy_datum.to_param, :deploy_datum => { "agg_config" => "invalid value" }}, valid_session
        assigns(:deploy_datum).should eq(deploy_datum)
      end

      it "re-renders the 'edit' template" do
        deploy_datum = DeployDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeployDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => deploy_datum.to_param, :deploy_datum => { "agg_config" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested deploy_datum" do
      deploy_datum = DeployDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => deploy_datum.to_param}, valid_session
      }.to change(DeployDatum, :count).by(-1)
    end

    it "redirects to the deploy_data list" do
      deploy_datum = DeployDatum.create! valid_attributes
      delete :destroy, {:id => deploy_datum.to_param}, valid_session
      response.should redirect_to(deploy_data_url)
    end
  end

end
