require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TagTableSchemasController do

  # This should return the minimal set of attributes required to create a valid
  # TagTableSchema. As you add validations to TagTableSchema, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      "table" => "mytable",
      "version" => "trunk",
      "owner" => "sandbox",
      "table_fields_attributes"=>
      {
        "1359542151595"=>
        {"group"=>"key",
         "label"=>"domain",
         "name"=>"domain",
         "field_type"=>"input"},
        "1359542161209"=>
        {"group"=>"value",
         "label"=>"pattern",
         "name"=>"pattern",
         "field_type"=>"input"}
      }
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TagTableSchemasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET show" do
    it "assigns the requested tag_table_schema as @tag_table_schema" do
      tag_table_schema = TagTableSchema.create! valid_attributes
      get :show, {:id => tag_table_schema.to_param}, valid_session
      assigns(:tag_table_schema).should eq(tag_table_schema)
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tag_table_schema" do
      tag_table_schema = TagTableSchema.create! valid_attributes
      expect {
        delete :destroy, {:id => tag_table_schema.to_param}, valid_session
      }.to change(TagTableSchema, :count).by(-1)
    end

    it "redirects to the tag_table_schemas list" do
      tag_table_schema = TagTableSchema.create! valid_attributes
      delete :destroy, {:id => tag_table_schema.to_param}, valid_session
      response.should redirect_to(table_schemas_url)
    end
  end

end
